### ISSUE TITLE
clone and run and fail

### ISSUE THREAD

**Issue by EasonPai** [dart-lang/sample-todomvc-polymer#11]
I cloned latest source and trying to run index.html with Dartium, then I get this error message right away.

Environment:
Windows 7
dart sdk x64 v1.13.0
Webstorm 10.0.4

```
Exception: Uncaught Error: Unsupported operation: Cannot provide `reflectedType` of instance of generic type 'List'.
Stack Trace:
#0      InstantiatedGenericClassMirrorImpl.reflectedType (package:reflectable/src/reflectable_transformer_based.dart:713:5)
#1      _getPropertyInfoForType (package:polymer/src/common/polymer_descriptor.dart:210:46)
#2      _buildPropertiesObject.<anonymous closure> (package:polymer/src/common/polymer_descriptor.dart:58:24)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#4      _buildPropertiesObject (package:polymer/src/common/polymer_descriptor.dart:56:16)
#5      createPolymerDescriptor (package:polymer/src/common/polymer_descriptor.dart:26:19)
#6      PolymerRegister.initialize (package:polymer/src/common/polymer_register.dart:19:36)
#7      loadInitializers.<anonymous closure>.<anonymous closure> (package:initialize/src/static_loader.dart:46:32)
#8      _runInitQueue (package:initialize/initialize.dart:35:24)
#9      _runInitQueue.<anonymous closure> (package:initialize/initialize.dart:38:26)
#10     _RootZone.runUnary (dart:async/zone.dart:1166)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:577)
#13     _Future._completeWithValue (dart:async/future_impl.dart:368)
#14     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:422)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#16     _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#17     _ScheduleImmediateHelper._handleMutation (dart:html:42567)
```

**Comment by EasonPai** [comment]
oops, this is an issue of reflectable
https://github.com/dart-lang/polymer-dart/issues/651

**Comment by eernstg** [comment]
It is certainly the getter `reflectedType` from a mirror class in package reflectable that fails. But when it is not possible to deliver the reflected type, the method `hasReflectedType` returns false. In this situation, the caller (package:polymer/src/common/polymer_descriptor.dart:210:46) should not call `reflectedType`.

Presumably this problem arises because the code around package:polymer/src/common/polymer_descriptor.dart:210:46 relies on the old semantics of `reflectedType` (where this method was more forgiving, but semantically not well-defined), such that the checks for `hasReflectedType` could be omitted in all the scenarios which were actually in use (because it would return true in all those situations).

The cure would be to modify polymer_descriptor.dart such that it only calls `reflectedType` when `hasReflectedType` returns true. When it returns false, the newer versions of reflectable (version 0.4.0 and up) offer an additional pair `hasDynamicReflectedType` and `dynamicReflectedType` where `hasDynamicReflectedType` will return true in a number of cases where `hasReflectedType` returns false; this pair of methods deal with the fully dynamic instantiation of generic types, which can be obtained in a number of cases where the precise instantiation is not available.

For instance, if `reflectedType` was used to get the `Type` value for the type annotation `List<E>` of a given variable/field/parameter in an instance of `C<int>` for some generic class `C<E>` then it should deliver a representation for `List<int>`, but that is impossible: we still lack the primitives needed to apply a generic class to a list of actual type arguments at runtime. But `dynamicReflectedType` would be able to return the fully dynamic instantiation `List<dynamic>` (same thing as `List`).

Note that issue https://github.com/dart-lang/polymer-dart/issues/651 is concerned with the situation a while ago, up to the point where version 0.4.0 was published. It contains historical material (in the comments from the beginning and down to the one starting 'Reflectable 0.4.0 has been published..'; the remaining comments there are on other topics). You may want to read that in order to get more background information, but it will not contribute anything new to this issue.

**Comment by jakemac53** [comment]
This package had an outdated reflectable dependency, I have updated it and everything seems to work fine now.
